services:
  mongo:
    image: mongo
    restart: always
    
  zookeeper:
    container_name: kafka-zookeeper
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka-server
    image: wurstmeister/kafka:2.12-2.5.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  catangamemanager.api:
    build:      
      context: .
      dockerfile: CatanGame/CatanGameInternal/CatanGameManager.API/Dockerfile
